spring:  profiles:    include:    - default;smart    active:    - smart---spring:  config:    activate:      on-profile:      - default
hr:
  raise:
    dflt:
      percent: 5      ---spring:  config:    activate:      on-profile:      - smarthr:  raise:    smrt:      levels: 3      criteria1: 2.5      percent1: 2      criteria2: 5      percent2: 5      criteria3: 10      percent3: 10